name: Cleanup Old Images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * 0'

jobs:
  delete-old-versions:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Cleanup rep2 images
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'rep2'
          package-type: 'container'
          delete-only-untagged-versions: 'false'
          min-versions-to-keep: 3

      - name: Cleanup rep2-extra images
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'rep2-extra'
          package-type: 'container'
          delete-only-untagged-versions: 'false'
          min-versions-to-keep: 3

      - name: Cleanup rep2-base images
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'rep2-base'
          package-type: 'container'
          delete-only-untagged-versions: 'false'
          min-versions-to-keep: 3

      - name: Cleanup rep2-base-extra images
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'rep2-base-extra'
          package-type: 'container'
          delete-only-untagged-versions: 'false'
          min-versions-to-keep: 3
